/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basededatos;

/**
 *
 * @author JOSAFAT
 */
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.Configuracion;
import util.MySQL;
public class Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
         this.setVisible(true);
        this.setLocationRelativeTo(null);
        MostrarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblcliente = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jcliente = new javax.swing.JTable();
        btnagregar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnPrincipal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TXTbuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblcliente.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblcliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcliente.setText("Cliente");

        jcliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "Direccion", "Telefono", "Estado"
            }
        ));
        jScrollPane2.setViewportView(jcliente);

        btnagregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btneditar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btneditar.setText("Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btneliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnPrincipal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPrincipal.setText("Principal");
        btnPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Buscar Codigo o Nombre:");

        TXTbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTbuscarActionPerformed(evt);
            }
        });
        TXTbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTbuscarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblcliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblcliente)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TXTbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        Configuracion.titulo ="Agregar Cliente";
        Configuracion.accion=1;
        new GestionCliente(this, true);
        MostrarTabla();
        
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        seleccionar_fila();
       if (Configuracion.id.length()>0) {
            Configuracion.titulo ="Editar Cliente";
            Configuracion.accion=2;
            new GestionCliente(this, true);
            MostrarTabla();
        }
        
    }//GEN-LAST:event_btneditarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        seleccionar_fila();
       
        if (Configuracion.id.length()>0){
            Configuracion.titulo ="Eliminar Cliente";
            Configuracion.accion=3;
            new GestionCliente(this, false);
            MostrarTabla();
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipalActionPerformed
    new Principal();
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnPrincipalActionPerformed

    private void TXTbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTbuscarKeyPressed
       
        String sql = "SELECT * FROM cliente WHERE codigoC LIKE '%" + TXTbuscar.getText() + "%' "
        + "OR nombreC LIKE '%" + TXTbuscar.getText() + "%'";
   
        String [] titulos = {"#","Codigo", "Nombre", "Apellido", "Direccion", "Telefono", "Estado"};
        ResultSet rs = null;
        DefaultTableModel tabla = new DefaultTableModel(null, titulos);
        rs=Configuracion.conexion.consutaSQL(sql);
        int x=0;
                try
                {
                    int  nf =ControlCliente.getRowsCliente();
                    Object[][] filas = new String [nf][7];
                    while (rs.next()) {
                        filas[x][0] =(x+1) + "";
                        filas[x][1] = rs.getString("codigoC");
                        filas[x][2] = rs.getString("nombreC");
                        filas[x][3] = rs.getString("apellidoC");
                        filas[x][4] = rs.getString("direccion");
                        filas[x][5] = rs.getInt("telefono") + "";
                        filas[x][6] = rs.getString("estado");
                        x++;
                    }
                    tabla.setDataVector(filas, titulos);
                    jcliente.setModel(tabla);
                } catch (SQLException ex)
                {
                    System.out.println("ERROR AL BUSCAR LOS DATOS : " + ex.getMessage());
                    Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex); 
                    }
    }//GEN-LAST:event_TXTbuscarKeyPressed

    private void TXTbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTbuscarActionPerformed

  private void seleccionar_fila(){
        int fila = -1;
         Configuracion.id = "";
        if (jcliente.getSelectedRowCount()==1) 
             fila = jcliente.getSelectedRow();
        else 
            JOptionPane.showMessageDialog(this, "selecionar solo un elemento");
        if (fila>-1) 
            
        Configuracion.id=(String )jcliente.getValueAt(fila, 1);
        System.out.println(Configuracion.id);
    }
    
 private void MostrarTabla(){
     String [] titulo = {"#","Codigo", "Nombre", "Apellido", "Direccion", "Telefono", "Estado"};
     DefaultTableModel tabla = new DefaultTableModel();
     ResultSet rs = ControlCliente.mostrarCliente();
     int x=0;
     try {
         int  nf =ControlCliente.getRowsCliente();
         Object[][] filas = new String [nf][7];
         while (rs.next()) {
           filas[x][0] =(x+1) + "";
           filas[x][1] = rs.getString("codigoC");
           filas[x][2] = rs.getString("nombreC");
           filas[x][3] = rs.getString("apellidoC");
           filas[x][4] = rs.getString("direccion");
           filas[x][5] = rs.getInt("telefono") + "";
           filas[x][6] = rs.getString("estado");
           x++;
         }
         tabla.setDataVector(filas, titulo);
         jcliente.setModel(tabla);
     } catch (SQLException ex) {
          Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
     }
 }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTbuscar;
    private javax.swing.JButton btnPrincipal;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jcliente;
    private javax.swing.JLabel lblcliente;
    // End of variables declaration//GEN-END:variables
}
