/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basededatos;



import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.Configuracion;
import util.MySQL;

/**
 *
 * @author JOSAFAT
 */
public class Producto extends javax.swing.JFrame {

    /**
     * Creates new form Producto
     */
    public Producto() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        MostrarTabla();
        //this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblproducto = new javax.swing.JLabel();
        btneliminar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jProducto = new javax.swing.JTable();
        btnagregar = new javax.swing.JButton();
        btnPrincipal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TXTbuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblproducto.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblproducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblproducto.setText("Productos");

        btneliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btneditar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btneditar.setText("Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        jProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Cantidad", "Precio", "Categoria"
            }
        ));
        jScrollPane2.setViewportView(jProducto);

        btnagregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btnPrincipal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPrincipal.setText("Principal");
        btnPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Buscar Codigo o Nombre:");

        TXTbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTbuscarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblproducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblproducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TXTbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        Configuracion.titulo ="Agregar Productos";
        Configuracion.accion=1;
        new GestionProducto(this, true);
         MostrarTabla();
    // TODO add your handling code here:
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        seleccionar_fila();
        if (Configuracion.id.length()>0) {
        Configuracion.titulo ="Editar Productos";
        Configuracion.accion=2;
        new GestionProducto(this, true); 
        MostrarTabla();
        }
              // TODO add your handling code here:
    }//GEN-LAST:event_btneditarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        seleccionar_fila();
        if (Configuracion.id.length()>0) {
        Configuracion.titulo ="Eliminar Productos";
        Configuracion.accion=3;
        new GestionProducto(this, true);   
        MostrarTabla();
        }
            
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipalActionPerformed
       new Principal();
         dispose();
    }//GEN-LAST:event_btnPrincipalActionPerformed

    private void TXTbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTbuscarKeyPressed
       
        String sql = "SELECT * FROM producto WHERE codigo LIKE '%" + TXTbuscar.getText() + "%' "
        + "OR nombre LIKE '%" + TXTbuscar.getText() + "%'";
         
        
        String [] titulos = {"#","Codigo", "Nombre", "Cantidad", "Precio", "Categoria"};
        ResultSet rs = null;
        DefaultTableModel tabla = new DefaultTableModel(null, titulos);
         rs=Configuracion.conexion.consutaSQL(sql);
          int x=0;
        try
        {
            int  nf =ControlProducto.getRows();
         Object[][] filas = new String [nf][6];
         while (rs.next()) {
           filas[x][0] =(x+1) + "";
           filas[x][1] = rs.getString("codigo");
           filas[x][2] = rs.getString("nombre");
           filas[x][3] = rs.getInt("cantidad") + "";
           filas[x][4] = rs.getDouble("precio") + "";
           filas[x][5] = rs.getString("categoria");
            x++;
            }
           tabla.setDataVector(filas, titulos);
         jProducto.setModel(tabla);
        } catch (SQLException ex)
        {
            System.out.println("ERROR AL BUSCAR LOS DATOS : " + ex.getMessage());
             Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TXTbuscarKeyPressed

    private void seleccionar_fila(){
        int fila = -1;
        Configuracion.id = "";
        if (jProducto.getSelectedRowCount()==1) 
             fila = jProducto.getSelectedRow();
        else 
            JOptionPane.showMessageDialog(this, "selecionar solo un elemento");
        if (fila>-1) 
            
        Configuracion.id=(String) jProducto.getValueAt(fila, 1);
        System.out.println(Configuracion.id);
    }
    
 private void MostrarTabla(){
     String [] titulo = {"#","Codigo", "Nombre", "Cantidad", "Precio", "Categoria"};
     DefaultTableModel tabla = new DefaultTableModel();
     ResultSet rs = ControlProducto.mostrar();
     int x=0;
     try {
         int  nf =ControlProducto.getRows();
         Object[][] filas = new String [nf][6];
         while (rs.next()) {
           filas[x][0] =(x+1) + "";
           filas[x][1] = rs.getString("codigo");
           filas[x][2] = rs.getString("nombre");
           filas[x][3] = rs.getInt("cantidad") + "";
           filas[x][4] = rs.getDouble("precio") + "";
           filas[x][5] = rs.getString("categoria");
           x++;
         }
         tabla.setDataVector(filas, titulo);
         jProducto.setModel(tabla);
     } catch (SQLException ex) {
          Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
     }
 }
 
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTbuscar;
    private javax.swing.JButton btnPrincipal;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable jProducto;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblproducto;
    // End of variables declaration//GEN-END:variables
}
