/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basededatos;

/**
 *
 * @author JOSAFAT
 */
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.Configuracion;
import util.MySQL;
public class Proveedor extends javax.swing.JFrame {

    /**
     * Creates new form Proveedor
     */
    public Proveedor() {
        initComponents();
         this.setVisible(true);
        this.setLocationRelativeTo(null);
        MostrarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblproveedor = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jProveedor = new javax.swing.JTable();
        btnagregar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnPrincipal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TXTbuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblproveedor.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblproveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblproveedor.setText("Proveedor");

        jProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Telefono", "Vendedor"
            }
        ));
        jScrollPane2.setViewportView(jProveedor);

        btnagregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btneditar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btneditar.setText("Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btneliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnPrincipal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPrincipal.setText("Principal");
        btnPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Buscar Codigo o Nombre:");

        TXTbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTbuscarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblproveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblproveedor)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TXTbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        Configuracion.titulo ="Agregar Proveedor";
        Configuracion.accion=1;
        new GestionProveedor(this, true);
        MostrarTabla();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
      seleccionar_fila();
        if (Configuracion.id.length()>0) {
              Configuracion.titulo ="Editar Proveedor";
            Configuracion.accion=2;
            new GestionProveedor(this, true);
            MostrarTabla();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btneditarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        seleccionar_fila();
        if (Configuracion.id.length()>0) {
            Configuracion.titulo ="Eliminar Proveedor";
            Configuracion.accion=3;
            new GestionProveedor(this, true);
            MostrarTabla();
        }

    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipalActionPerformed
       new Principal();
         dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_btnPrincipalActionPerformed

    private void TXTbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTbuscarKeyPressed

        String sql = "SELECT * FROM proveedor WHERE codigoProv LIKE '%" + TXTbuscar.getText() + "%' "
        + "OR nombreProv LIKE '%" + TXTbuscar.getText() + "%'";

         String [] titulos = {"#","Codigo", "Nombre", "Telefono", "Vendedor"};
        ResultSet rs = null;
        DefaultTableModel tabla = new DefaultTableModel(null, titulos);
        rs=Configuracion.conexion.consutaSQL(sql);
        int x=0;
        try
        {
           int  nf =ControlProveedor.getRowsProveedor();
         Object[][] filas = new String [nf][5];
         while (rs.next()) {
           filas[x][0] =(x+1) + "";
           filas[x][1] = rs.getString("codigoProv");
           filas[x][2] = rs.getString("nombreProv");
           filas[x][3] = rs.getInt("telefono") + "";
           filas[x][4] = rs.getString("vendedor");
           x++;
         }
         tabla.setDataVector(filas, titulos);
         jProveedor.setModel(tabla);
        } catch (SQLException ex)
        {
            System.out.println("ERROR AL BUSCAR LOS DATOS : " + ex.getMessage());
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TXTbuscarKeyPressed

    private void seleccionar_fila(){
        int fila = -1;
         Configuracion.id = "";
        if (jProveedor.getSelectedRowCount()==1) 
             fila = jProveedor.getSelectedRow();
        else 
            JOptionPane.showMessageDialog(this, "selecionar solo un elemento");
        if (fila>-1) 
        
        Configuracion.id=(String )jProveedor.getValueAt(fila, 1);
        System.out.println(Configuracion.id);
    }
    
 private void MostrarTabla(){
     String [] titulo = {"#","Codigo", "Nombre", "Telefono", "Vendedor"};
     DefaultTableModel tabla = new DefaultTableModel();
     ResultSet rs = ControlProveedor.mostrarProveedor();
     int x=0;
     try {
         int  nf =ControlProveedor.getRowsProveedor();
         Object[][] filas = new String [nf][5];
         while (rs.next()) {
           filas[x][0] =(x+1) + "";
           filas[x][1] = rs.getString("codigoProv");
           filas[x][2] = rs.getString("nombreProv");
           filas[x][3] = rs.getInt("telefono") + "";
           filas[x][4] = rs.getString("vendedor");
           x++;
         }
         tabla.setDataVector(filas, titulo);
         jProveedor.setModel(tabla);
     } catch (SQLException ex) {
          Logger.getLogger(Proveedor.class.getName()).log(Level.SEVERE, null, ex);
     }
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTbuscar;
    private javax.swing.JButton btnPrincipal;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable jProveedor;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblproveedor;
    // End of variables declaration//GEN-END:variables
}
